export const VIEWS = [
  { imgSrc: '/assets/img/players/Ashikhmin-Tikhon.jpg', name: 'Ашихмин Тихон', newRole: 'Нападающий Bradford Rattlers, Канада', prevTeam: 'Györi ETO HC U21, Венгрия', id: 'ashikhmin-tikhon' },
  { imgSrc: '/assets/img/players/Babets-Danil1.jpg', name: 'Бабец Данил', newRole: 'Вратарь Polonia Bytom, Польша', prevTeam: 'Капитан Ступино U18, Россия', id: 'babets-danil' },
  { imgSrc: '/assets/img/players/Boktaev-Ernest.jpg', name: 'Боктаев Эрнест', newRole: 'Защитник New Tecumseth Civics, Канада', prevTeam: 'Созвездие Москва U16, Россия', id: 'boktaev-ernest' },
  { imgSrc: '/assets/img/players/Buduev-Roman.jpg', name: 'Будуев Роман', newRole: 'Защитник Toronto Titans U16 AAA, Канада', prevTeam: 'Металлург Магнитогорск U15, Россия', id: 'buduev-roman' },
  { imgSrc: '/assets/img/players/Ershov-Nikolay.jpg', name: 'Ершов Николай', newRole: 'Вратарь Bradford Rattlers, Канада', prevTeam: 'Синяя Птица Москва U16, Россия', id: 'ershov-nikolay' },
  { imgSrc: '/assets/img/players/Ispalatov-Egor.jpg', name: 'Испалатов Егор', newRole: 'Защитник Toronto Titans U16 AAA, Канада', prevTeam: 'Янтарь Москва U15, Россия', id: 'ispalatov-egor' },
  { imgSrc: '/assets/img/players/Kabanov-Denis.jpg', name: 'Кабанов Денис', newRole: 'Защитник Bradford Rattlers, Канада', prevTeam: 'Капитан Ступино U18, Россия', id: 'kabanov-denis' },
  { imgSrc: '/assets/img/players/Kabataev-Egor1.jpg', name: 'Кабатаев Егор', newRole: 'Нападающий Dunaújvárosi Acélbikák, Венгрия', prevTeam: 'Барыс Нур-Султан U20, Казахстан', id: 'kabataev-egor' },
  { imgSrc: '/assets/img/players/Korotaev-Iliya1.jpg', name: 'Коротаев Илья', newRole: 'Нападающий Györi ETO HC U21k, Венгрия', prevTeam: 'Капитан Ступино U18, Россия', id: 'korotaev-iliya' },
  { imgSrc: '/assets/img/players/Levitskiy-Stepan.jpg', name: 'Левицкий Степан', newRole: 'Нападающий Bradford Rattlers, Канада', prevTeam: 'Орбита Зеленоград U18, Россия', id: 'levitskiy-stepan' },
  { imgSrc: '/assets/img/players/Pochuev-Daniil2.jpg', name: 'Почуев Даниил', newRole: 'Нападающий New Tecumseth Civics, Канада', prevTeam: 'Рубин Тюмень U18, Россия', id: 'pochuev-daniil' },
  { imgSrc: '/assets/img/players/Rudskoy-Egor1.jpg', name: 'Рудской Егор', newRole: 'Защитник Polonia Bytom, Польша', prevTeam: 'Капитан Ступино U18, Россия', id: 'rudskoy-egor' },
  { imgSrc: '/assets/img/players/Sinodkin-Denis1.jpg', name: 'Синодкин Денис', newRole: 'Нападающий Györi ETO HC U21, Венгрия', prevTeam: 'Сокол Курск U18, Россия', id: 'sinodkin-denis' },
  { imgSrc: '/assets/img/players/Smirnov-Anton.jpg', name: 'Смирнов Антон', newRole: 'Нападающий Toronto Titans U16 AAA, Канада', prevTeam: 'Ястребы Москва U16, Россия', id: 'smirnov-anton' },
  { imgSrc: '/assets/img/players/Smirnov-Ilia1.jpg', name: 'Смирнов Илья', newRole: 'Нападающий Polonia Bytom, Польша', prevTeam: 'СКА ХКД Колпино U18, Россия', id: 'smirnov-ilia' },
  { imgSrc: '/assets/img/players/Sobolev-Nikita1.jpg', name: 'Соболев Никита', newRole: 'Нападающий New Tecumseth Civics, Канада', prevTeam: 'Морские Львы Москва U18, Россия', id: 'sobolev-nikita' },
  { imgSrc: '/assets/img/players/Suschenko-Sergei.jpg', name: 'Сущенко Сергей', newRole: 'Нападающий Toronto Titans U16 AAA, Канада', prevTeam: 'Белые Медведи Москва U15, Россия', id: 'suschenko-sergei' },
  { imgSrc: '/assets/img/players/Frolov-Vadim.jpg', name: 'Фролов Вадим', newRole: 'Нападающий Bradford Rattlers, Канада', prevTeam: 'Дизелист Пенза НМХЛ, Россия', id: 'frolov-vadim' },
];
